spring:
  application:
    name: insurance-campaign-api

  datasource:
    url: jdbc:postgresql://localhost:5432/insurance_campaign_api
    username: postgres
    password: pt5458
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8086
  servlet:
    context-path: /api/1.0

jwt:
  secret: mySecretKey
  expireMs: 30000 #30 sec
  refreshExpireMs: 60000 #1 min



