version: '2'

services:
  app:
    image: 'insurance-campaign-api:latest'
    build:
      context: ../..
    container_name: app
    depends_on:
      - db
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test-prod-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pt5458
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - insurance-campaign-network

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pt5458
      - POSTGRES_DB=test-prod-db
    networks:
      - insurance-campaign-network

